# https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx

controller:
  config:
    use-proxy-protocol: "true"
  service:
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    labels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
  extraArgs:
      enable-ssl-passthrough: ""
