apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cafe
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: deployments/cafe
    repoURL: https://github.com/halfpastjohn/umbrella-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  syncOptions:
  - CreateNamespace=true
