---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorapi
  labels:
    app: colorapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: colorapi
  template:
    metadata:
      labels:
        app: colorapi
    spec:
      containers:
      - name: colorapi
        image: particule/simplecolorapi:1.0
        ports:
        - name: web
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: colorapi
  labels:
    app: colorapi
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: colorapi


# apiVersion: argoproj.io/v1alpha1
# kind: Rollout # argo CRD - basically the same as `Deployment`
# metadata:
# name: kairos
# labels:
#   app: kairos
# spec:
# # argo stuff
# strategy:
#   maxSurge: 10
#   canary:
#     canaryService: canary-kairos
#     stableService: kairos
#     trafficRouting:
#       nginx:
#          stableIngress: kairos-ingress  # required
#          annotationPrefix: argorollout.nginx.ingress.kubernetes.io # optional
#          additionalIngressAnnotations: #optional
#            canary-by-header: X-Canary
#     steps:
#     - setWeight: 25
#     - pause:
#         duration: "90s"
#     - setWeight: 50
#     - pause:
#         duration: "90s"
# replicas: 4
# revisionHistoryLimit: 2
# selector:
#   matchLabels:
#     app: kairos
# template:
#   metadata:
#     labels:
#       app: kairos
#   spec:
#     containers:
#     - name: kairos
#       image: nginxdemos/nginx-kairos:plain-text
#       imagePullPolicy: Always
#       ports:
#       - name: web
#         containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
# name: kairos
# spec:
# ports:
# - port: 80
#   targetPort: 8080
# selector:
#   app: kairos
# ---
# apiVersion: v1
# kind: Service
# metadata:
# name: canary-kairos
# spec:
# ports:
# - port: 80
#   targetPort: 8080
# selector:
#   app: kairos
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
# name: kairos-ingress
# annotations:
#   kubernetes.io/ingress.class: "nginx" # Allows the ingress controller to discover this ingress
#   nginx.ingress.kubernetes.io/rewrite-target: /$2 # Remove first path segment and send to service root
# spec:
# rules:
# - http:
#     paths:
#     - path: /kairos(/|$)(.*)
#       backend:
#         serviceName: kairos
#         servicePort: 80
