apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 9.14.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
